# Generated by Django 5.0.3 on 2024-03-12 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50)),
                ('title', models.CharField(choices=[('Push-ups', 'Push-ups'), ('Pull-ups', 'Pull-ups'), ('Squats', 'Squats'), ('Deadlifts', 'Deadlifts'), ('Bench Press', 'Bench Press'), ('Dumbbell Rows', 'Dumbbell Rows'), ('Burpees', 'Burpees'), ('Jumping Jacks', 'Jumping Jacks'), ('Plank', 'Plank'), ('Russian Twists', 'Russian Twists'), ('Mountain Climbers', 'Mountain Climbers'), ('Lunges', 'Lunges'), ('Leg Press', 'Leg Press'), ('Calf Raises', 'Calf Raises'), ('Leg Curls', 'Leg Curls'), ('Lat Pulldowns', 'Lat Pulldowns'), ('Tricep Dips', 'Tricep Dips'), ('Bicep Curls', 'Bicep Curls'), ('Shoulder Press', 'Shoulder Press')], max_length=100)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('target_muscles', models.CharField(max_length=200)),
                ('equipment_required', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('achieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=50)),
                ('goals', models.TextField()),
                ('session_duration', models.IntegerField(default=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
                ('personal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.personalplan')),
            ],
        ),
        migrations.AddField(
            model_name='personalplan',
            name='exercises',
            field=models.ManyToManyField(through='workout.PersonalPlanExercise', to='workout.exercise'),
        ),
    ]
