# Generated by Django 5.0.3 on 2024-03-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='photo',
            new_name='image',
        ),
    ]
